version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the cypress-orb
  cypress: cypress-io/cypress@1.26.0
# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          record: true
          parallel: false
