version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the cypress-orb
  cypress: cypress-io/cypress@1.26.0
# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - cypress/run:
          browser: chrome
          yarn: true
          start: yarn start:ci
          parallel: true
          parallelism: 2
          ci-build-d: ${CIRCLE_SHA1:0:8}
